# Generated by Django 4.2.2 on 2023-06-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='baeminImage',
            field=models.ImageField(blank=True, upload_to='productsQR/%Y/%m/%d'),
        ),
    ]
