# Generated by Django 4.2.2 on 2023-06-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='first name', max_length=50),
            preserve_default=False,
        ),
    ]
